/*
--- REMOVE THE DUPS -- START 
WITH DUPS AS
( SELECT [DOCUMENT_NUMBER],[NUMBER],[ITEM], ROW_NUMBER() OVER (PARTITION BY [DOCUMENT_NUMBER],[NUMBER],[ITEM] 
                                                                ORDER BY [DOCUMENT_NUMBER]) AS RN
  FROM [MD].[DOCUMENT_NUMBER]
)
DELETE FROM DUPS WHERE RN > 1;
---- REMOVE THE DUPS --  END
*/


/*

SELECT [FI_DOCUMENT_NO], [FY_PERIOD],[LEVEL_NUMBER], COUNT(*) AS CNT
FROM  [TD].[FM_FI_LNITMS]	
GROUP BY [FI_DOCUMENT_NO], [FY_PERIOD],[LEVEL_NUMBER]
HAVING COUNT(*)>1

SELECT COUNT(*) FROM [TD].[FM_FI_LNITMS]

SELECT * FROM ETL.LOGGING;

*/

--TRUNCATE TABLE [TD].[FM_FI_LNITMS_DUPS]
--SELECT * FROM [TD].[FM_FI_LNITMS_DUPS]
------------------------------------------------------------------------------------------------

MERGE INTO [TD].[FM_FI_LNITMS_DUPS] TGT
	 USING  
	 (SELECT
	        FM.[DATA_AS_OF_DATE]
           ,FM.[DS_INSERT_DATE]
           ,FM.[DS_INSERT_TIME]
           ,FM.[DW_STATUS_IND]
           ,FM.[DOCUMENT_NUMBER]
           ,FM.[FM_DOC_NO]
           ,FM.[FM_ITEM]
           ,FM.[AMOUNT_TYPE]
           ,FM.[BUDGET_CATEGORY]
           ,FM.[FISCAL_YEAR]
           ,DUPS.[LEVEL_NUMBER] --- LEVEL_NUMBER
           ,FM.[FY_VARIANT]
           ,DUPS.[FY_PERIOD] ------- FY_PERIOD
           ,FM.[YCE]
           ,FM.[YEAR_OF_CASH_EFF]
           ,FM.[FM_POSTING_DATE]
           ,FM.[FM_AREA]
           ,FM.[FUND]
           ,FM.[FUNDS_CENTER]
           ,FM.[COMMITMENT_ITEM]
           ,FM.[FUNCTIONAL_AREA]
           ,FM.[FUNDED_PROGRAM]
           ,FM.[GRANT]
           ,FM.[CUSTOMER_FIELD]
           ,FM.[COMPANY_CODE]
           ,FM.[CHART_OF_ACCOUNTS]
           ,FM.[GL_ACCOUNT]
           ,FM.[CO_AREA]
           ,FM.[COST_CENTER]
           ,FM.[ORDER]
           ,FM.[WBS_ELEMENT]
           ,FM.[PROFIT_CENTER]
           ,FM.[FM_VALTYPE]
           ,FM.[VALUE_TYPE]
           ,FM.[BUS_TRANSACTION]
           ,FM.[STATISTICAL_ID]
           ,FM.[CF_LEVEL]
           ,FM.[CARRYFWDPREVYR]
           ,FM.[VENDOR]
           ,FM.[CUSTOMER]
           ,FM.[TEXT]
           ,FM.[CANCEL_ID]
           ,FM.[DOCUMENT_TYPE]
           ,FM.[POSTING_DATE]
           ,FM.[PMNT_DOC_COMP_CODE]
           ,FM.[FY_PMNT_DOC]
           ,FM.[PAYMENT_DOC_NO]
           ,FM.[PMNT_DOC_NO_ITEM]
           ,FM.[FI_DOC_NO_FY]
           ,DUPS.[FI_DOCUMENT_NO] ---FI_DOCUMENT_NO
           ,FM.[FI_DOCUMENT_ITEM]
           ,FM.[PRED_DOC_NO]
           ,FM.[PRED_DOC_ITEM]
           ,FM.[PRED_ORG]
           ,FM.[PREDECESSOR_AA]
           ,FM.[FM_AREA_CURR]
           ,FM.[FMAC_AMOUNT]
           ,FM.[EXPENDITURE_AMOUNT]
           ,FM.[TRANS_CURRENCY]
           ,FM.[TC_AMOUNT]
           ,FM.[ARCHIVE]
           ,FM.[OBJECT_NUMBER]
           ,FM.[REF_TRANSACTN]
           ,FM.[REF_DOCUMENT]
           ,FM.[BUDGET_PERIOD]
           ,FM.[BUSINESS_AREA]
           ,FM.[PAYMENT_STATUS]
           ,FM.LEDGER
		   ,FM.TRANACTION_NO
		   ,FM.POSTING_DAY
		   ,FM.OBJECT_NUMBER_1
		   ,FM.BASE_UNIT
		   ,FM.REFERENCE_KEY_3
		   ,FM.PREDECESSOR_DT
		   ,FM.REF_TRANSACTN_1
		   ,FM.REF_DOCUMENT_NO
		   ,FM.DOCUMENT_DATE
		   ,FM.DOC_HEADER_TEXT
		   ,FM.REFFISCALYEAR
		   ,FM.DELINDICTR
		   ,FM.REFERENC_ORG_UN
		   ,FM.REFCOMPANYCODE
		   ,FM.ODQ_CHANGEMODE
		   ,FM.ODQ_ENTITYCNTR
		   ,FM.[SOURCEEFFTIMESTAMP]
           ,FM.[SOURCEBATCHPROCESSID]
           ,FM.[SOURCERECORDSTATUS]

FROM [TD].[FM_FI_LNITMS] FM JOIN 

(SELECT [FI_DOCUMENT_NO],[FY_PERIOD],[LEVEL_NUMBER], 
			ROW_NUMBER() OVER (PARTITION BY [FI_DOCUMENT_NO],[FY_PERIOD],[LEVEL_NUMBER]
                                       ORDER BY [FI_DOCUMENT_NO]) AS RN FROM [TD].[FM_FI_LNITMS] 
) DUPS ON
   FM.[FI_DOCUMENT_NO]=DUPS.[FI_DOCUMENT_NO] AND
   FM.[FY_PERIOD]=DUPS.[FY_PERIOD] AND
   FM.[LEVEL_NUMBER]=DUPS.[LEVEL_NUMBER]
WHERE DUPS.RN > 1

) SRC
	 ON
    TGT.[FI_DOCUMENT_NO]=SRC.[FI_DOCUMENT_NO] AND
	TGT.[FY_PERIOD]=SRC.[FY_PERIOD] AND
	TGT.[LEVEL_NUMBER]=SRC.[LEVEL_NUMBER]
WHEN MATCHED THEN 
UPDATE SET
    TGT.[FM_DOC_NO]=SRC.[FM_DOC_NO],
   	TGT.[FM_ITEM]=SRC.[FM_ITEM],
	TGT.[AMOUNT_TYPE]=SRC.[AMOUNT_TYPE],
	TGT.[BUDGET_CATEGORY]=SRC.[BUDGET_CATEGORY],
	TGT.[FISCAL_YEAR]=SRC.[FISCAL_YEAR],
	TGT.[LEVEL_NUMBER]=SRC.[LEVEL_NUMBER],
	TGT.[FY_VARIANT]=SRC.[FY_VARIANT],
	TGT.[YCE]=SRC.[YCE],
	TGT.[YEAR_OF_CASH_EFF]=SRC.[YEAR_OF_CASH_EFF],
	TGT.[FM_POSTING_DATE]=SRC.[FM_POSTING_DATE],
	TGT.[GRANT]=SRC.[GRANT],
	TGT.[CUSTOMER_FIELD]=SRC.[CUSTOMER_FIELD],
	TGT.[COMPANY_CODE]=SRC.[COMPANY_CODE],
	TGT.[CHART_OF_ACCOUNTS]=SRC.[CHART_OF_ACCOUNTS],
	TGT.[GL_ACCOUNT]=SRC.[GL_ACCOUNT],
	TGT.[CO_AREA]=SRC.[CO_AREA],
	TGT.[COST_CENTER]=SRC.[COST_CENTER],
	TGT.[ORDER]=SRC.[ORDER],
	TGT.[WBS_ELEMENT]=SRC.[WBS_ELEMENT],
	TGT.[PROFIT_CENTER]=SRC.[PROFIT_CENTER],
	TGT.[FM_VALTYPE]=SRC.[FM_VALTYPE],
	TGT.[VALUE_TYPE]=SRC.[VALUE_TYPE],
	TGT.[BUS_TRANSACTION]=SRC.[BUS_TRANSACTION],
	TGT.[STATISTICAL_ID]=SRC.[STATISTICAL_ID],
	TGT.[CF_LEVEL]=SRC.[CF_LEVEL],
	TGT.[CARRYFWDPREVYR]=SRC.[CARRYFWDPREVYR],
	TGT.[VENDOR]=SRC.[VENDOR],
	TGT.[CUSTOMER]=SRC.[CUSTOMER],
	TGT.[TEXT]=SRC.[TEXT],
	TGT.[CANCEL_ID]=SRC.[CANCEL_ID],
	TGT.[DOCUMENT_TYPE]=SRC.[DOCUMENT_TYPE],
	TGT.[POSTING_DATE]=SRC.[POSTING_DATE],
	TGT.[PMNT_DOC_COMP_CODE]=SRC.[PMNT_DOC_COMP_CODE],
	TGT.[FY_PMNT_DOC]=SRC.[FY_PMNT_DOC],
	TGT.[PAYMENT_DOC_NO]=SRC.[PAYMENT_DOC_NO],
	TGT.[PMNT_DOC_NO_ITEM]=SRC.[PMNT_DOC_NO_ITEM],
	TGT.[FI_DOC_NO_FY]=SRC.[FI_DOC_NO_FY],
	TGT.[FI_DOCUMENT_NO]=SRC.[FI_DOCUMENT_NO],
	TGT.[FI_DOCUMENT_ITEM]=SRC.[FI_DOCUMENT_ITEM],
	TGT.[PRED_DOC_NO]=SRC.[PRED_DOC_NO],
	TGT.[PRED_DOC_ITEM]=SRC.[PRED_DOC_ITEM],
	TGT.[PRED_ORG]=SRC.[PRED_ORG],
	TGT.[PREDECESSOR_AA]=SRC.[PREDECESSOR_AA],
	TGT.[FM_AREA_CURR]=SRC.[FM_AREA_CURR],
	TGT.[FMAC_AMOUNT]=SRC.[FMAC_AMOUNT],
	TGT.[TRANS_CURRENCY]=SRC.[TRANS_CURRENCY],
	TGT.[TC_AMOUNT]=SRC.[TC_AMOUNT],
	TGT.[ARCHIVE]=SRC.[ARCHIVE],
	TGT.[OBJECT_NUMBER]=SRC.[OBJECT_NUMBER],
	TGT.[REF_TRANSACTN]=SRC.[REF_TRANSACTN],
	TGT.[REF_DOCUMENT]=SRC.[REF_DOCUMENT],
	TGT.[BUDGET_PERIOD]=SRC.[BUDGET_PERIOD],
	TGT.[PAYMENT_STATUS]=SRC.[PAYMENT_STATUS],
	TGT.LEDGER=SRC.LEDGER,
	TGT.TRANACTION_NO=SRC.TRANACTION_NO,
	TGT.POSTING_DAY=SRC.POSTING_DAY,
	TGT.OBJECT_NUMBER_1=SRC.OBJECT_NUMBER_1,
	TGT.BASE_UNIT=SRC.BASE_UNIT,
	TGT.REFERENCE_KEY_3=SRC.REFERENCE_KEY_3,
	TGT.PREDECESSOR_DT=SRC.PREDECESSOR_DT,
	TGT.REF_TRANSACTN_1=SRC.REF_TRANSACTN_1,
	TGT.REF_DOCUMENT_NO=SRC.REF_DOCUMENT_NO,
	TGT.DOCUMENT_DATE=SRC.DOCUMENT_DATE,
	TGT.DOC_HEADER_TEXT=SRC.DOC_HEADER_TEXT,
	TGT.REFFISCALYEAR=SRC.REFFISCALYEAR,
	TGT.DELINDICTR=SRC.DELINDICTR,
	TGT.REFERENC_ORG_UN=SRC.REFERENC_ORG_UN,
	TGT.REFCOMPANYCODE=SRC.REFCOMPANYCODE,
	TGT.ODQ_CHANGEMODE=SRC.ODQ_CHANGEMODE,
	TGT.ODQ_ENTITYCNTR=SRC.ODQ_ENTITYCNTR,
	TGT.[SOURCERECORDSTATUS]='U', 
	TGT.[SOURCEEFFTIMESTAMP]=GETDATE()
	
WHEN NOT MATCHED THEN
INSERT 
(
    [DATA_AS_OF_DATE],
    [DS_INSERT_DATE],
    [DS_INSERT_TIME],
    [DW_STATUS_IND],
    [DOCUMENT_NUMBER],
    [FM_DOC_NO] ,
  	[FM_ITEM],
	[AMOUNT_TYPE] ,
	[BUDGET_CATEGORY],
	[FISCAL_YEAR],
	[LEVEL_NUMBER] ,
	[FY_VARIANT] ,
	[FY_PERIOD] ,
	[YCE] ,
	[YEAR_OF_CASH_EFF] ,
	[FM_POSTING_DATE] ,
	[FM_AREA] ,
	[FUND] ,
	[FUNDS_CENTER] ,
	[COMMITMENT_ITEM] ,
	[FUNCTIONAL_AREA],
	[FUNDED_PROGRAM] ,
	[GRANT] ,
	[CUSTOMER_FIELD] ,
	[COMPANY_CODE] ,
	[CHART_OF_ACCOUNTS] ,
	[GL_ACCOUNT] ,
	[CO_AREA] ,
	[COST_CENTER] ,
	[ORDER],
	[WBS_ELEMENT] ,
	[PROFIT_CENTER] ,
	[FM_VALTYPE] ,
	[VALUE_TYPE] ,
	[BUS_TRANSACTION] ,
	[STATISTICAL_ID] ,
	[CF_LEVEL] ,
	[CARRYFWDPREVYR] ,
	[VENDOR] ,
	[CUSTOMER] ,
	[TEXT] ,
	[CANCEL_ID],
	[DOCUMENT_TYPE] ,
	[POSTING_DATE] ,
	[PMNT_DOC_COMP_CODE] ,
	[FY_PMNT_DOC] ,
	[PAYMENT_DOC_NO] ,
	[PMNT_DOC_NO_ITEM] ,
	[FI_DOC_NO_FY] ,
	[FI_DOCUMENT_NO] ,
	[FI_DOCUMENT_ITEM] ,
	[PRED_DOC_NO],
	[PRED_DOC_ITEM] ,
	[PRED_ORG] ,
	[PREDECESSOR_AA] ,
	[FM_AREA_CURR] ,
	[FMAC_AMOUNT] ,
	[EXPENDITURE_AMOUNT],
	[TRANS_CURRENCY] ,
	[TC_AMOUNT] ,
	[ARCHIVE] ,
	[OBJECT_NUMBER] ,
	[REF_TRANSACTN] ,
	[REF_DOCUMENT] ,
	[BUDGET_PERIOD] ,
	[BUSINESS_AREA] ,
	[PAYMENT_STATUS] ,
	LEDGER,
	TRANACTION_NO,
	POSTING_DAY,
	OBJECT_NUMBER_1,
	BASE_UNIT,
	REFERENCE_KEY_3,
	PREDECESSOR_DT,
	REF_TRANSACTN_1,
	REF_DOCUMENT_NO,
	DOCUMENT_DATE,
	DOC_HEADER_TEXT,
	REFFISCALYEAR,
	DELINDICTR,
	REFERENC_ORG_UN,
	REFCOMPANYCODE,
	ODQ_CHANGEMODE,
	ODQ_ENTITYCNTR,
	[SOURCEEFFTIMESTAMP] ,
	[SOURCEBATCHPROCESSID],
	[SOURCERECORDSTATUS] 

)

VALUES( 
    SRC.[DATA_AS_OF_DATE],
    SRC.[DS_INSERT_DATE],
    SRC.[DS_INSERT_TIME],
    SRC.[DW_STATUS_IND],
    SRC.[DOCUMENT_NUMBER],
    SRC.[FM_DOC_NO],
    SRC.[FM_ITEM],
	SRC.[AMOUNT_TYPE] ,
	SRC.[BUDGET_CATEGORY],
	SRC.[FISCAL_YEAR],
	SRC.[LEVEL_NUMBER] ,
	SRC.[FY_VARIANT] ,
	SRC.[FY_PERIOD] ,
	SRC.[YCE] ,
	SRC.[YEAR_OF_CASH_EFF] ,
	SRC.[FM_POSTING_DATE] ,
	SRC.[FM_AREA] ,
	SRC.[FUND] ,
	SRC.[FUNDS_CENTER] ,
	SRC.[COMMITMENT_ITEM] ,
	SRC.[FUNCTIONAL_AREA],
	SRC.[FUNDED_PROGRAM] ,
	SRC.[GRANT] ,
	SRC.[CUSTOMER_FIELD] ,
	SRC.[COMPANY_CODE] ,
	SRC.[CHART_OF_ACCOUNTS] ,
	SRC.[GL_ACCOUNT] ,
	SRC.[CO_AREA] ,
	SRC.[COST_CENTER] ,
	SRC.[ORDER],
	SRC.[WBS_ELEMENT] ,
	SRC.[PROFIT_CENTER] ,
	SRC.[FM_VALTYPE] ,
	SRC.[VALUE_TYPE] ,
	SRC.[BUS_TRANSACTION] ,
	SRC.[STATISTICAL_ID] ,
	SRC.[CF_LEVEL] ,
	SRC.[CARRYFWDPREVYR] ,
	SRC.[VENDOR] ,
	SRC.[CUSTOMER] ,
	SRC.[TEXT] ,
	SRC.[CANCEL_ID],
	SRC.[DOCUMENT_TYPE] ,
	SRC.[POSTING_DATE] ,
	SRC.[PMNT_DOC_COMP_CODE] ,
	SRC.[FY_PMNT_DOC] ,
	SRC.[PAYMENT_DOC_NO] ,
	SRC.[PMNT_DOC_NO_ITEM] ,
	SRC.[FI_DOC_NO_FY] ,
	SRC.[FI_DOCUMENT_NO] ,
	SRC.[FI_DOCUMENT_ITEM] ,
	SRC.[PRED_DOC_NO],
	SRC.[PRED_DOC_ITEM] ,
	SRC.[PRED_ORG] ,
	SRC.[PREDECESSOR_AA] ,
	SRC.[FM_AREA_CURR] ,
	SRC.[FMAC_AMOUNT] ,
	SRC.[EXPENDITURE_AMOUNT],
	SRC.[TRANS_CURRENCY] ,
	SRC.[TC_AMOUNT] ,
	SRC.[ARCHIVE] ,
	SRC.[OBJECT_NUMBER] ,
	SRC.[REF_TRANSACTN] ,
	SRC.[REF_DOCUMENT] ,
	SRC.[BUDGET_PERIOD] ,
	SRC.[BUSINESS_AREA] ,
	SRC.[PAYMENT_STATUS] ,
	SRC.LEDGER,
	SRC.TRANACTION_NO,
	SRC.POSTING_DAY,
	SRC.OBJECT_NUMBER_1,
	SRC.BASE_UNIT,
	SRC.REFERENCE_KEY_3,
	SRC.PREDECESSOR_DT,
	SRC.REF_TRANSACTN_1,
	SRC.REF_DOCUMENT_NO,
	SRC.DOCUMENT_DATE,
	SRC.DOC_HEADER_TEXT,
	SRC.REFFISCALYEAR,
	SRC.DELINDICTR,
	SRC.REFERENC_ORG_UN,
	SRC.REFCOMPANYCODE,
	SRC.ODQ_CHANGEMODE,
	SRC.ODQ_ENTITYCNTR,
	GETDATE(),
	'1',
	'L'

);
---------------REMOVE DUPS FROM LNITMS-----------------------------------------------------------------------------------------------
WITH DUPS_IN_LNITMS AS
(SELECT [FI_DOCUMENT_NO],[FY_PERIOD],[LEVEL_NUMBER], ROW_NUMBER() OVER (PARTITION BY [FI_DOCUMENT_NO],[FY_PERIOD],[LEVEL_NUMBER]
                                                                           ORDER BY [FI_DOCUMENT_NO]) AS RN
FROM [TD].[FM_FI_LNITMS] 
)
DELETE FROM DUPS_IN_LNITMS WHERE RN > 1;
---------------REMOVE DUPS FROM DUPS-----------------------------------------------------------------------------------------------
WITH DUPS_IN_DUPS AS
(SELECT [FI_DOCUMENT_NO],[FY_PERIOD],[LEVEL_NUMBER], ROW_NUMBER() OVER (PARTITION BY [FI_DOCUMENT_NO],[FY_PERIOD],[LEVEL_NUMBER]
                                                                            ORDER BY [FI_DOCUMENT_NO]) AS RN
FROM [TD].[FM_FI_LNITMS_DUPS] 
)
DELETE FROM DUPS_IN_DUPS WHERE RN > 1;
----------------------------------------------------------------------------------------------------------------------------------



 