---------------------------------- TABLES TO TRUNCATE IN PREPARATION FOR FULL LOAD ---------------
TRUNCATE TABLE [ETL].[CNTRL]
TRUNCATE TABLE [ETL].LOGGING
TRUNCATE TABLE [ETL].[LOGGING_ARCHIVE]
TRUNCATE TABLE [TD].[FM_BDGT_ENTR] 
TRUNCATE TABLE [TD].[FM_CMMT_LNITMS]
TRUNCATE TABLE [TD].[FM_FI_LNITMS]
TRUNCATE TABLE [TD].[FM_PARKED_LNITMS]
TRUNCATE TABLE [TD].[FM_FI_LNITMS_X]
TRUNCATE TABLE [TD].[FM_FI_LNITMS_DUPS]

--------------------------------------------------------------------------------------------------

