SELECT * FROM revenue.SkuPrice

SELECT SKUID, COUNT(DISTINCT ContractID) CNT
FROM [cube].[F_ProductRevenueNAV]
GROUP BY SKUID
HAVING COUNT(DISTINCT ContractID)>1
ORDER BY COUNT(DISTINCT ContractID) DESC