USE [Staging]
GO
/****** Object:  StoredProcedure [dbo].[usp_CreateStraightLineWaterfall2]    Script Date: 11/16/2017 2:27:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

drop table dbo.StraightLineContracts

CREATE TABLE dbo.StraightLineContracts (
	[ContractID] [int]  NULL,
	[Waterfall_Amt] [money] NULL,
	[Waterfall_Stub_Amt] [money] NULL,
	[Contract_Final_Amt] [money] NULL,
	StraightLine_Flg bit null
) ON [PRIMARY]

--------------------------------------------------
EXEC  [dbo].[usp_CreateStraightLineWaterfall2]
---------------------------------------------------
SELECT * FROM dbo.StraightLineContracts

*/

ALTER PROC [dbo].[usp_CreateStraightLineWaterfall2]
@CONTRACTID INT=175582
AS
------  Declare Period vars
DECLARE @CURRENT_TERM INT
DECLARE @ESCALATION_MTH_START INT
DECLARE @TRUE_INI_PRD INT
DECLARE @TRUE_INI_PRD_ADJ INT
DECLARE @TRUE_ESC_PRD INT
DECLARE @TRUE_ESC_PRD_ADJ INT
DECLARE @TRUE_TERM NUMERIC(18,4)
------- Declare flags vars
DECLARE @STRAIGHT_LINE_CONTRACT_FLG BIT=0 
DECLARE @STUB_INVOLVED_FLG BIT
------ Declare money vars
DECLARE @CONTRACT_INITAL_AMT MONEY
DECLARE @CONTRACT_FINAL_AMT MONEY
DECLARE @CONTRACT_ESCALATION_AMT MONEY
DECLARE @CONTRACT_FINAL_MTH_AMT MONEY
DECLARE @CONTRACT_REG_MTH_AMT MONEY
DECLARE @CONTRACT_ESC_MTH_AMT MONEY 
------- Declare Dates vars
DECLARE @CURRENT_TERM_START_DATE DATE
DECLARE @FIRST_MTH_START_DATE DATE
------- Declare Stub vars
DECLARE @STUB_DIFF_DAYS INT
DECLARE @STUB_FRACTION NUMERIC(18,4)
DECLARE @STUB_MTH_TOTAL_DAYS INT
DECLARE @STUB_START DATE
DECLARE @STUB_END DATE
DECLARE @STUB_START_DAY INT
DECLARE @STUB_AMT MONEY
DECLARE @WATERFALL_AMT MONEY
DECLARE @WATERFALL_STUB_AMT MONEY

--------------------------  Period calculations start below ---------------

SELECT @CURRENT_TERM=datediff(mm,MIN(CurrentTermStartDate),MAX(RenewalDate)) 
FROM Staging..LineItem  WHERE ContractID=@CONTRACTID
SELECT @CURRENT_TERM CURRENT_TERM;

------------------------- Stub Calcualtions start below ---------------------

SELECT @STUB_START=MIN(CurrentTermStartDate)  FROM Staging..LineItem  WHERE ContractID=@CONTRACTID;
SELECT @STUB_START STUB_START

SELECT @STUB_END=MAX(EOMONTH(CurrentTermStartDate)) FROM Staging..LineItem  WHERE ContractID=@CONTRACTID;
SELECT @STUB_END STUB_END

SELECT @STUB_MTH_TOTAL_DAYS=DAY(@STUB_END)
SELECT @STUB_MTH_TOTAL_DAYS STUB_MTH_TOTAL_DAYS

SELECT @STUB_START_DAY=DAY(@STUB_START)
SELECT @STUB_START_DAY STUB_START_DAY

SELECT @STUB_DIFF_DAYS=(@STUB_MTH_TOTAL_DAYS-@STUB_START_DAY)+1
SELECT @STUB_DIFF_DAYS STUB_DIFF_DAYS

SELECT @STUB_FRACTION=CAST(@STUB_DIFF_DAYS AS NUMERIC(18,4))/CAST(@STUB_MTH_TOTAL_DAYS AS NUMERIC(18,4))
SELECT @STUB_FRACTION STUB_FRACTION

SELECT @ESCALATION_MTH_START=MAX(FirstEscalationMonth) 
FROM Staging..LineItemEscalation LE 
     JOIN Staging..LineItem L ON LE.LineItemID=L.LineItemID
                                          WHERE ContractID=@CONTRACTID
SELECT @ESCALATION_MTH_START ESCALATION_MTH_START

IF @ESCALATION_MTH_START < @CURRENT_TERM 
  BEGIN    SET @STRAIGHT_LINE_CONTRACT_FLG=1  END

SELECT @STRAIGHT_LINE_CONTRACT_FLG STRAIGHT_LINE_CONTRACT_FLG

---------------------------- Monetary Calcualtions Start Below -------------
--------------------- Step 1. calculate the initial amount (contract value before escalations ) 
SELECT @CONTRACT_REG_MTH_AMT=SUM(ISNULL(DiscountedMonthlyPrice,0))
FROM Staging..LineItem  WHERE ContractID=@CONTRACTID
SELECT @CONTRACT_REG_MTH_AMT CONTRACT_REG_MTH_AMT

--------------------- Step2 calculate the escalation amount (value of escalations )
SELECT @CONTRACT_ESCALATION_AMT=SUM(ISNULL(LE.EscalationAmount,0))
FROM Staging..LineItemEscalation LE 
     JOIN Staging..LineItem L ON LE.LineItemID=L.LineItemID
                                          WHERE ContractID=@CONTRACTID
SELECT @CONTRACT_ESCALATION_AMT CONTRACT_ESCALATION_AMT
SET @CONTRACT_FINAL_MTH_AMT= @CONTRACT_REG_MTH_AMT + @CONTRACT_ESCALATION_AMT
SET @CONTRACT_ESC_MTH_AMT = @CONTRACT_FINAL_MTH_AMT
SELECT @CONTRACT_ESC_MTH_AMT CONTRACT_ESC_MTH_AMT
----- Assemble the true Periods ----------------
SET @TRUE_INI_PRD=(@ESCALATION_MTH_START-1)
SET @TRUE_INI_PRD_ADJ = @TRUE_INI_PRD - 1
SET @TRUE_ESC_PRD=@CURRENT_TERM-@TRUE_INI_PRD
SET @TRUE_ESC_PRD_ADJ = @TRUE_ESC_PRD + 1
SET @TRUE_TERM=CAST(@CURRENT_TERM AS NUMERIC(18,4)) + CAST(@STUB_FRACTION AS NUMERIC(18,4))

---- Assemble the Initial Stub Amount ---------

SET @STUB_AMT=@CONTRACT_REG_MTH_AMT * @STUB_FRACTION
SELECT @STUB_AMT STUB_AMT

----  Assemble the true Amounts ---------------
SET @CONTRACT_INITAL_AMT= @CONTRACT_REG_MTH_AMT * @TRUE_INI_PRD_ADJ
SET @CONTRACT_ESCALATION_AMT=@CONTRACT_FINAL_MTH_AMT * @TRUE_ESC_PRD_ADJ
SELECT @CONTRACT_ESCALATION_AMT CONTRACT_ESCALATION_AMT

SET @CONTRACT_FINAL_AMT = @CONTRACT_INITAL_AMT + @CONTRACT_ESCALATION_AMT + @STUB_AMT
SET @WATERFALL_AMT = @CONTRACT_FINAL_AMT / @TRUE_TERM
SET @WATERFALL_STUB_AMT = @WATERFALL_AMT * @STUB_FRACTION

----------- DISPLAY INTERM RESULTS --------------------
SELECT @CONTRACTID CONTRACTID
SELECT @CONTRACT_FINAL_AMT CONTRACT_FINAL_AMT
SELECT @CONTRACT_ESCALATION_AMT CONTRACT_ESCALATION_AMT
SELECT @CONTRACT_INITAL_AMT CONTRACT_INITAL_AMT
SELECT @TRUE_TERM TRUE_TERM
SELECT @WATERFALL_AMT WATERFALL_AMT
SELECT @WATERFALL_STUB_AMT WATERFALL_STUB_AMT
SELECT @TRUE_INI_PRD_ADJ TRUE_INI_PRD_ADJ
SELECT @TRUE_ESC_PRD_ADJ TRUE_ESC_PRD_ADJ
-------------------------------------------------------
---- Perform final Insert of the Results for that Contract
INSERT [dbo].[StraightLineContracts] ([ContractID],[Waterfall_Amt],[Waterfall_Stub_Amt],[Contract_Final_Amt],StraightLine_Flg)
SELECT @CONTRACTID,@WATERFALL_AMT,@WATERFALL_STUB_AMT,@CONTRACT_FINAL_AMT,@STRAIGHT_LINE_CONTRACT_FLG


------------------------------
-----------------------------

CREATE PROCEDURE [dbo].[uspProcessStraightLineContracts]
AS

DECLARE @CURRENT_CONTRACTID INT

 DECLARE C CURSOR FOR
 SELECT DISTINCT [ContractID] FROM RevPro..[Active_SOFile]
 ORDER BY [ContractID]
  
 OPEN C
 FETCH c into @CURRENT_CONTRACTID
 WHILE @@FETCH_STATUS = 0
 BEGIN
   EXEC [dbo].[usp_CreateStraightLineWaterfall2] @CURRENT_CONTRACTID
FETCH c into @CURRENT_CONTRACTID
 END

 CLOSE C
 DEALLOCATE C

DELETE FROM [dbo].[StraightLineContracts] where Contract_Final_Amt IS NULL;
DELETE FROM [dbo].[StraightLineContracts] where StraightLine_Flg=0; 








